apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: devops-tools
  labels:
    app: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fastapi-app
        version: IMAGE_TAG_PLACEHOLDER
    spec:
      containers:
      - name: fastapi-app
        image: IMAGE_NAME_PLACEHOLDER
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: APP_VERSION
          value: "VERSION_PLACEHOLDER"
        - name: BUILD_NUMBER
          value: "BUILD_PLACEHOLDER"
        - name: ENVIRONMENT
          value: "development"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  namespace: devops-tools
  labels:
    app: fastapi-app
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 32100
      protocol: TCP